# Generated by Django 4.0.4 on 2022-07-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionrequest',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
