version: '3.8'

services:
  web:
    container_name: web
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  test:
    container_name: test_server
    build: ./app
    command: python test_server.py
    volumes:
    - ./test_server:/user/src/test_server
    ports:
    - 8001:8001
    env_file:
      - ./.env.dev

volumes:
  postgres_data: